export const programs = [
  {
    id: 1,
    title: 'Comfort Airlines',
    description:
      'Generates flight plans and simulates airline operations for evaluation and profit optimization.',
    link: 'https://github.com/matthewjburton/comfort-airlines',
    tags: [
      { label: 'Python', iconClass: 'devicon-python-plain' },
      { label: 'MariaDB', iconClass: 'devicon-mariadb-plain' },
      { label: 'Docker', iconClass: 'devicon-docker-plain' },
    ],
    year: 2024,
  },
  {
    id: 2,
    title: 'Business Case Form',
    description: 'A web app for evaluating potential business investments.',
    link: 'https://udig-business-case-form-test.netlify.app/',
    tags: [
      { label: 'React', iconClass: 'devicon-react-plain' },
      { label: 'Typescript', iconClass: 'devicon-typescript-plain' },
      { label: 'GraphQL', iconClass: 'devicon-graphql-plain' },
      { label: 'PostgreSQL', iconClass: 'devicon-postgresql-plain' },
      { label: 'Figma', iconClass: 'devicon-figma-plain' },
    ],
    year: 2023,
  },
  {
    id: 3,
    title: 'Fine Dining Bot',
    description:
      "A webscraping bot for making reservations at High Point University's fine dining restaurants.",
    link: 'https://github.com/matthewjburton/reservation-bot',
    tags: [
      { label: 'Python', iconClass: 'devicon-python-plain' },
      { label: 'Selenium', iconClass: 'devicon-selenium-plain' },
    ],
    year: 2024,
  },
  {
    id: 4,
    title: 'Blackjack',
    description: 'A CLI Blackjack game.',
    link: 'https://github.com/matthewjburton/blackjack',
    tags: [{ label: 'C++', iconClass: 'devicon-cplusplus-plain' }],
    year: 2022,
  },
  {
    id: 5,
    title: 'Skate Park Finder',
    description:
      'A mobile app that locates the nearest skate parks based on your location.',
    link: 'https://github.com/matthewjburton/skate-park-finder',
    tags: [{ label: 'Java', iconClass: 'devicon-java-plain' }],
    year: 2022,
  },
  {
    id: 6,
    title: 'Endless Breakout',
    image: 'Images/Games/Endless Breakout.png',
    description: 'Infinite arcade brick breaker.',
    link: 'https://matt-burton.itch.io/endless-breakout',
    tags: [
      { label: 'Unity', iconClass: 'devicon-unity-plain' },
      { label: 'C#', iconClass: 'devicon-csharp-plain' },
      { label: 'Illustrator', iconClass: 'devicon-illustrator-plain' },
    ],
    year: 2023,
  },
  {
    id: 7,
    title: 'Messaging App',
    description: 'Send messages between clients across a server.',
    link: 'https://github.com/matthewjburton/network-app',
    tags: [{ label: 'C', iconClass: 'devicon-c-plain' }],
    year: 2023,
  },
  {
    id: 8,
    title: 'Super Massive',
    description: 'Made in 48 hours for the GMTK game jam.',
    link: 'https://matt-burton.itch.io/super-massive',
    tags: [
      { label: 'C#', iconClass: 'devicon-csharp-plain' },
      { label: 'Unity', iconClass: 'devicon-unity-plain' },
    ],
    year: 2024,
  },
  {
    id: 9,
    title: 'Caves of Combat',
    image: 'Images/Games/Head Hunter.png',
    description: 'An action roguelike platformer.',
    link: 'https://cavesofcombat.com',
    tags: [
      { label: 'C#', iconClass: 'devicon-csharp-plain' },
      { label: 'Unity', iconClass: 'devicon-unity-plain' },
      { label: 'React', iconClass: 'devicon-react-plain' },
      { label: 'Typescript', iconClass: 'devicon-typescript-plain' },
    ],
    year: 2025,
  },
  {
    id: 10,
    title: 'Full Stack Open',
    description:
      'A collection of web app solutions made alongside course provided by the University of Helsinki.',
    link: 'https://github.com/matthewjburton/full-stack-open',
    tags: [
      { label: 'React', iconClass: 'devicon-react-plain' },
      { label: 'Javascript', iconClass: 'devicon-javascript-plain' },
      { label: 'Typescript', iconClass: 'devicon-typescript-plain' },
      { label: 'Node', iconClass: 'devicon-nodejs-plain' },
      { label: 'Express', iconClass: 'devicon-express-original' },
      { label: 'PostgreSQL', iconClass: 'devicon-postgresql-plain' },
      { label: 'Docker', iconClass: 'devicon-docker-plain' },
      { label: 'MongoDB', iconClass: 'devicon-mongodb-plain' },
      { label: 'Vite', iconClass: 'devicon-vite-plain' },
      { label: 'Vitest', iconClass: 'devicon-vitest-plain' },
      { label: 'Redux', iconClass: 'devicon-redux-plain' },
      { label: 'Graphql', iconClass: 'devicon-graphql-plain' },
      { label: 'Github Actions', iconClass: 'devicon-githubactions-plain' },
      { label: 'Playwright', iconClass: 'devicon-playwright-plain' },
      { label: 'Axios', iconClass: 'devicon-axios-plain' },
    ],
    year: 2024,
  },
  {
    id: 11,
    title: 'Company Dashboard',
    description: `A centralized landing page to connect AdvanceTEC's web apps.`,
    link: 'https://app.advancetecllc.com',
    tags: [
      { label: 'React', iconClass: 'devicon-react-plain' },
      { label: 'Typescript', iconClass: 'devicon-typescript-plain' },
      { label: 'Docker', iconClass: 'devicon-docker-plain' },
      { label: 'Vite', iconClass: 'devicon-vite-plain' },
      { label: 'Github Actions', iconClass: 'devicon-githubactions-plain' },
    ],
    year: 2024,
  },
  {
    id: 12,
    title: 'Expense Report',
    description:
      'A streamlined web form to submit and process employee expenses.',
    link: 'https://expense-report.advancetecllc.com',
    tags: [
      { label: 'React', iconClass: 'devicon-react-plain' },
      { label: 'Javascript', iconClass: 'devicon-javascript-plain' },
      { label: 'Typescript', iconClass: 'devicon-typescript-plain' },
      { label: 'Node', iconClass: 'devicon-nodejs-plain' },
      { label: 'Express', iconClass: 'devicon-express-original' },
      { label: 'Docker', iconClass: 'devicon-docker-plain' },
      { label: 'MongoDB', iconClass: 'devicon-mongodb-plain' },
      { label: 'Vite', iconClass: 'devicon-vite-plain' },
      { label: 'Vitest', iconClass: 'devicon-vitest-plain' },
      { label: 'Github Actions', iconClass: 'devicon-githubactions-plain' },
      { label: 'Playwright', iconClass: 'devicon-playwright-plain' },
      { label: 'Axios', iconClass: 'devicon-axios-plain' },
    ],
    year: 2024,
  },
  {
    id: 13,
    title: 'Inventory',
    description:
      'An inventory management system capable of tracking shipments, find materials, and scheduling prefabrication.',
    link: 'https://inventory.advancetecllc.com',
    tags: [
      { label: 'React', iconClass: 'devicon-react-plain' },
      { label: 'Javascript', iconClass: 'devicon-javascript-plain' },
      { label: 'Typescript', iconClass: 'devicon-typescript-plain' },
      { label: 'Node', iconClass: 'devicon-nodejs-plain' },
      { label: 'Express', iconClass: 'devicon-express-original' },
      { label: 'Docker', iconClass: 'devicon-docker-plain' },
      { label: 'PostgreSQL', iconClass: 'devicon-postgresql-plain' },
      { label: 'Vite', iconClass: 'devicon-vite-plain' },
      { label: 'Vitest', iconClass: 'devicon-vitest-plain' },
      { label: 'Github Actions', iconClass: 'devicon-githubactions-plain' },
      { label: 'Playwright', iconClass: 'devicon-playwright-plain' },
      { label: 'Axios', iconClass: 'devicon-axios-plain' },
    ],
    year: 2025,
  },
  // Add more programs as needed
]
